# Generated by Django 4.2.2 on 2023-06-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
                ('sort', models.PositiveIntegerField(max_length=128)),
            ],
        ),
    ]
