# Generated by Django 4.2.2 on 2023-06-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='sort',
            field=models.PositiveIntegerField(),
        ),
    ]
