# Generated by Django 4.2.2 on 2023-06-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_contactwithus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
