# Generated by Django 4.2.2 on 2023-06-15 01:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_events_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description_mini',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
