# Generated by Django 4.2.2 on 2023-06-15 01:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_events_description_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description_full',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='style',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
